### ISSUE TITLE
Please create packager for tally to allow us to build rpm

### ISSUE THREAD

**Issue by antonioodunuga1** [choria-io/tally#14]
We’ve decided to make use of choria tally and try to build and deploy it in house but are having some issues. We were able to successfully get tally working in choria-compose and view the metrics in a local instance of Prometheus and Grafana and found the metrics useful.
 
We noticed that tally is missing a packager folder along with it’s templates for the different EL versions to be able to build the tally rpm. Can you please create to unblock us? 

Thank you

**Comment by antonioodunuga1** [comment]
Looks good! Thanks for the quick turnaround.

I was getting the error and had to add 'CGO_ENABLED: "0"' environmental variable to remove the external dependancies. I hope this is okay?  

`gcc: error: unrecognized command line option '-m64'
`

After it was added, I was able to build the RPM locally.

**Comment by ripienaar** [comment]
Probsbly you tried to build the x86 build on docker for Apple cilicone mac. 

Build on a Linux machine and would be good. 

You tested the rpm is what you need?

**Comment by ripienaar** [comment]
will update the run command thanks.

The `logger_type = console` can be removed and I think if you swap the `logfile:` to `logfile = ..." it will probably work

**Comment by antonioodunuga1** [comment]
Oh.. I didn't notice that. 

Restarted and looks to be working as expected. Will test further and get back to you if I find anything else in the meantime. Thanks @ripienaar
